# -*- coding: utf-8 -*-
"""CourseTA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nqj7rJGTQEeh-4veqHMFEPWS2Npxyccl

#Course work (Text analysis)

###Sentiment analysis of posts from the VK-group "Netfleet"

Моя работа заключается в анализе тональности постов в ВК-группе по водному транспорту. Парсила посты я локально в jupyter и выгрузила в csv файл.
"""

!pip install emoji demoji googletrans==3.1.0a0 -q
!pip install pymorphy3 -q
!pip install transformers torch accelerate -q
!pip install wordcloud -q
!pip install imbalanced-learn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import re
import emoji
import demoji
from googletrans import Translator

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import pymorphy3
from tqdm.auto import tqdm
from wordcloud import WordCloud
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import RandomOverSampler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

from transformers import pipeline

demoji.download_codes()
translator = Translator()
tqdm.pandas()

"""##EDA

"""

df = pd.read_csv('vk_posts_group2.csv', header=None, names=['text'])
df.head()

df.shape

#удаляем пустые + строки из пробелов + супер короткие строки
df = df.dropna()

df = df[df['text'].str.strip() != '']

df['text'] = df['text'].astype(str)
df = df[df['text'].str.len() > 1]
df['text'] = df['text'].astype(str)

print(f'Таблица без пропущенных значений содержит {df.shape[0]} строк\n')

df = df.drop_duplicates(subset=['text'])

print(f'Таблица без повторяющихся постов содержит {df.shape[0]} строк\n')

"""**Посмотрим распределение длин постов**"""

df['length'] = df['text'].str.len()
df['length'].describe()

plt.figure(figsize=(10,6))
plt.hist(df['length'], bins=100, color='lightblue')
plt.xlim(0, 3000)
plt.title('Распределение длины постов')
plt.xlabel('Длина текста')
plt.ylabel('Количество постов')
plt.show()

import seaborn as sns

plt.figure(figsize=(15,5))
sns.kdeplot(df['length'], fill=True)
plt.xlim(0, 3000)
plt.title('Плотность распределения длины постов')
plt.show()

#самые короткие посты
df.sort_values('length').head(10)

#топ-10 длинных постов
df[['text', 'length']].sort_values('length').head(10)
df[['text', 'length']].sort_values('length', ascending=False).head(10)

"""###Обработка смайликов

Собираем смайлики для всех постов
"""

def extract_emojis(s):
    return ''.join(c for c in s if c in emoji.EMOJI_DATA)

set_text = df['text'].astype(str).tolist()

#список строк где каждая строка — только смайлики из поста
emoji_chat = [extract_emojis(s) for s in set_text]

df['emojis'] = emoji_chat

"""Декодирование смайликов"""

def emojis_to_desc_en(emo_str: str) -> str:
    #emo_str строка типа '😊'
    if not emo_str:
        return ''
    dict_emoj = demoji.findall(emo_str)  #возвращает словарь типа {'😊': 'смайлинг фейс'}

    res = []
    for key in dict_emoj.keys():
        res.append(dict_emoj[key])

    #склеиваем описания в одну строку
    return ' '.join(res)

df['emoji_desc_en'] = df['emojis'].apply(emojis_to_desc_en)

df[df['emojis'] != ''][['text', 'emojis', 'emoji_desc_en']].head(10)

"""Перевод описания смайликов на русский"""

translator = Translator()

def translate_to_ru(text: str) -> str:
    text = text.strip()
    if not text:
        return ''
    try:
        result = translator.translate(text, dest='ru')
        return result.text
    except:
        #если гугл шлет ошибки оставляем англ варик
        return text

df['emoji_desc_ru'] = df['emoji_desc_en'].progress_apply(translate_to_ru)

"""Соединяем текст постов и перевод смайликов"""

df['text_with_emoji'] = df['text'] + ' ' + df['emoji_desc_ru'].fillna('')

"""##Предобработка текстов"""

morph = pymorphy3.MorphAnalyzer()
stop_ru = set(stopwords.words("russian"))
stop_en = set(stopwords.words("english"))

def preprocess_text(text):
    if not isinstance(text, str):
        text = str(text)

    text = re.sub(r'http\S+', ' ', text)
    text = re.sub(r'#\S+', ' ', text)
    text = re.sub(r'\b(?:www\.)?\w+\.(?:ru|com|org|net|info|club|online|site|io|gov|edu)\b', ' ', text)
    text = re.sub(r"[^а-яА-ЯёЁa-zA-Z\s]", " ", text)
    text = text.lower()

    tokens = word_tokenize(text, language="russian")
    tokens = [w for w in tokens if w.isalpha()]

    #удаление стоп-слов, кроме "не"
    clean_tokens = []
    for w in tokens:
        if w == "не":
            clean_tokens.append(w)
            continue
        if w in stop_ru or w in stop_en:
            continue
        clean_tokens.append(w)

    lemmas = []
    for w in clean_tokens:
        if re.fullmatch(r"[а-яё]+", w):
            lemmas.append(morph.parse(w)[0].normal_form)
        elif re.fullmatch(r"[a-z]+", w):
            lemmas.append(w)
        else:
            continue

    lemmas = [w for w in lemmas if (len(w) > 1 or w == "не")]

    if lemmas:
        return " ".join(lemmas)

    #фолбэк
    text2 = re.sub(r"[^а-яА-ЯёЁa-zA-Z\s]", " ", text)
    out = " ".join([w for w in text2.split() if w.isalpha()])

    return out if out else ""

tqdm.pandas()
df['processed_text'] = df['text_with_emoji'].progress_apply(preprocess_text)

df[df['emojis'] != ''][['text', 'emojis', 'emoji_desc_ru', 'processed_text']].head()

"""##Описательная аналитика корпуса

Самые часто встречающиеся слова
"""

all_tokens = []

for text in df['processed_text']:
    tokens = re.findall(r'[а-яёa-z]+', str(text).lower())
    all_tokens.extend(tokens)

word_counts = Counter(all_tokens).most_common(50)
freq_df = pd.DataFrame(word_counts, columns=['слово', 'частота'])
freq_df = freq_df[freq_df['слово'] != 'не']  #чтобы "не" не забивало все

plt.figure(figsize=(10,5))
sns.barplot(data=freq_df.head(10), x='слово', y='частота', color = 'lightblue')
plt.title('Топ-10 самых частотных слов в корпусе')
plt.xlabel('Слово')
plt.ylabel('Частота')
plt.xticks(rotation=45)
plt.show()

"""Облако слов"""

text_all = " ".join(df['processed_text'])

text_all = " ".join([w for w in all_tokens if w != 'не']) #опять же тк будет лишним

wc = WordCloud(width=1200, height=600, background_color='white', collocations=False).generate(text_all)

plt.figure(figsize=(15,7))
plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.show()

"""Самые частые биграммы"""

#считаем биграммы
vec = CountVectorizer(ngram_range=(2, 2), min_df=5)
X_bi = vec.fit_transform(df['processed_text'])

#суммируем частоты биграмм и собираем таблицу
bi_df = pd.DataFrame({
    'биграмма': vec.get_feature_names_out(),
    'частота': X_bi.toarray().sum(axis=0)
})

bi_df = bi_df.sort_values('частота', ascending=False).reset_index(drop=True)
bi_df = bi_df[~bi_df['биграмма'].str.contains('восклицательный|знак|красный')]

plt.figure(figsize=(12, 6))
sns.barplot(data=bi_df.head(10), x='биграмма', y='частота', color='lightblue')
plt.title('Топ-10 биграмм', fontsize=14, pad=20)
plt.xlabel('Биграмма')
plt.ylabel('Частота')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""##Тональность с BERT"""

tqdm.pandas()

sentiment_model = pipeline("sentiment-analysis", model="seara/rubert-tiny2-russian-sentiment", return_all_scores=True)

THRESH = 0.45  #порог для positive/negative

def get_sentiment_thresh(text: str, thresh: float = THRESH) -> str:
    if not isinstance(text, str):
        text = str(text)
    text = text.strip()
    if not text:
        return "neutral"
    try:
        scores = sentiment_model(text)[0]   #список из dictов [{'label':..., 'score':...}, ...]
        #преобразуем в удобный вид: label -> score
        score_dict = {d['label'].lower(): d['score'] for d in scores}
        pos = score_dict.get('positive', 0.0)
        neg = score_dict.get('negative', 0.0)
        neu = score_dict.get('neutral', 0.0)

        #если positive или negative >= thresh — считаем это эмоцией
        #если оба выше порога — берём из них тот, что больше
        if pos >= thresh and neg < thresh:
            return 'positive'
        elif neg >= thresh and pos < thresh:
            return 'negative'
        elif pos >= thresh and neg >= thresh:
            #оба выше порога — берём более сильный
            return 'positive' if pos >= neg else 'negative'
        else:
            #ни позитив, ни негатив не дотянули — считаем нейтральным
            return 'neutral'

    except Exception:
        return "neutral"

df['sentiment'] = df['text_with_emoji'].progress_apply(get_sentiment_thresh)
df[['text', 'sentiment']].head()

"""**Проверяем, что есть позитивные и негативные посты**"""

df['sentiment'].value_counts(), df['sentiment'].value_counts(normalize=True).round(3)

sent_counts = df['sentiment'].value_counts()

plt.figure(figsize=(6,4))
sent_counts.plot(kind='bar', color = 'lightblue')
plt.title('Распределение тональностей постов')
plt.xlabel('Класс тональности')
plt.ylabel('Количество постов')
plt.xticks(rotation=0)
plt.show()

"""##Обучение моделей

###LogisticRegression с оверсэмплингом
"""

VOCABULARY_SIZE = 10000

X = df['processed_text']
y = df['sentiment']

#общий train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Распределение классов в исходном train:")
print(y_train.value_counts())

#оверсэмплинг
train_df = pd.DataFrame({'text': X_train, 'sentiment': y_train})

neu = train_df[train_df['sentiment'] == 'neutral']
pos = train_df[train_df['sentiment'] == 'positive']
neg = train_df[train_df['sentiment'] == 'negative']

#целевой размер - нейтралка
target_per_class = len(neu)

pos_up = pos.sample(target_per_class, replace=True, random_state=42)
neg_up = neg.sample(target_per_class, replace=True, random_state=42)

train_balanced = pd.concat([neu, pos_up, neg_up]) \
    .sample(frac=1, random_state=42) \
    .reset_index(drop=True)

print("\nРаспределение классов в upsampled train:")
print(train_balanced['sentiment'].value_counts())

#общий tf-idf
tfidf_vectorizer = TfidfVectorizer(max_features=VOCABULARY_SIZE, ngram_range=(1, 2))

#признаки для исходного несбалансированного train/test
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

#признаки для для варианта с oversampling
X_train_tfidf_up = tfidf_vectorizer.transform(train_balanced['text'])

print("\nРазмерность TF-IDF матрицы train (upsampled):", X_train_tfidf_up.shape)

#1 логрег без обработки дисбаланса
logreg_plain = LogisticRegression(max_iter=1000, random_state=42)
logreg_plain.fit(X_train_tfidf, y_train)

y_pred_plain = logreg_plain.predict(X_test_tfidf)

print("Логистическая регрессия без обработки дисбаланса")
print("Accuracy (plain logreg):", accuracy_score(y_test, y_pred_plain))
print(classification_report(y_test, y_pred_plain, digits=4))


#2 логрег с балансировкой весов
logreg_bal = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
logreg_bal.fit(X_train_tfidf, y_train)

y_pred_bal = logreg_bal.predict(X_test_tfidf)

print("\nЛогистическая регрессия с балансировкой весов")
print("Accuracy (logreg + weights):", accuracy_score(y_test, y_pred_bal))
print(classification_report(y_test, y_pred_bal, digits=4))


#3 логрег с ovesampling
logreg_up = LogisticRegression(max_iter=1000, random_state=42)
logreg_up.fit(X_train_tfidf_up, train_balanced['sentiment'])

y_pred_up = logreg_up.predict(X_test_tfidf)

print("\nЛогистическая регрессия с oversampling")
print("Accuracy (logreg + oversampling):", accuracy_score(y_test, y_pred_up))
print(classification_report(y_test, y_pred_up, digits=4))

"""очевидно, что лучше всех себя показала модель с оверсэмплингом, тк она дает более ровное качество по всем трем классам. сохраняется приемлемая общая точность (0.79), но модель уже не забывает про редкий негативный класс.

**Посмотрим какие ошибки допустила моделька**
"""

cm_logreg = confusion_matrix(y_test, y_pred_up, labels=labels)

cm_logreg_df = pd.DataFrame(
    cm_logreg,
    index=[f"true_{lbl}" for lbl in labels],
    columns=[f"pred_{lbl}" for lbl in labels]
)

print("\nМатрица ошибок (logreg + oversampling):")
print(cm_logreg_df)

logreg_errors = (y_test.values != y_pred_up).sum()
print("\nКоличество ошибок (logreg + oversampling):", logreg_errors)

"""###MLP+oversampling"""

le = LabelEncoder()
le.fit(y)

#кодируем train/test метки
y_train_enc = le.transform(y_train)
y_test_enc = le.transform(y_test)

print(X_train_tfidf.shape, X_test_tfidf.shape)
print(pd.Series(y_train_enc).value_counts())

ros = RandomOverSampler(random_state=42)
X_train_over, y_train_over = ros.fit_resample(X_train_tfidf, y_train_enc)

print("Форма после oversampling:", X_train_over.shape)
print(pd.Series(y_train_over).value_counts())

X_train_over_dense = X_train_over.astype('float32').toarray()
X_test_dense = X_test_tfidf.astype('float32').toarray()

num_features = X_train_over_dense.shape[1]
num_classes = len(le.classes_)

print(num_features, num_classes)
tf.random.set_seed(42)

nn_model = Sequential([
    Dense(256, activation='relu', input_shape=(num_features,)),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

nn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

nn_model.summary()

history = nn_model.fit(
    X_train_over_dense,
    y_train_over,
    epochs=10,
    batch_size=64,
    validation_split=0.2,
    verbose=2
)

y_pred_proba = nn_model.predict(X_test_dense)
y_pred_nn = y_pred_proba.argmax(axis=1)

print("Accuracy (NN + oversampling):", accuracy_score(y_test_enc, y_pred_nn), 4)

print(classification_report(
    y_test_enc,
    y_pred_nn,
    target_names=le.classes_,
    digits=4
))

"""Посмотрим какие ошибки допустила модель"""

cm_nn = confusion_matrix(y_test_enc, y_pred_nn)

cm_nn_df = pd.DataFrame(
    cm_nn,
    index=[f"true_{lbl}" for lbl in le.classes_],
    columns=[f"pred_{lbl}" for lbl in le.classes_]
)

print("\nМатрица ошибок (нейронная сеть):")
print(cm_nn_df)

#кол-во ошибок
nn_errors = (y_test_enc != y_pred_nn).sum()
print("\nКоличество ошибок (нейронная сеть):", nn_errors)